name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        *We are very excited to meet you at the 2022 OHBM Brainhack 🎉* *To submit a project, you need to be an attendee of the 2022 OHBM Brainhack. We ask you to register first over [here](http://www.humanbrainmapping.org/HackathonReg/). Thank you!*
        
        *We have prepared this template to help with your project submission. Here is how to proceed:*
         1. *Before fill the template check [the guideline](https://github.com/ohbm/hackathon2022/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md). Be sure to include as many information as possible*
         2. *Submit the issue*
         3. *Check items in the checklist*
         4. *Once you are done (at least all 'required' items must be provided), please delete the "Guidelines" section add a comment saying 'hi @ohbm/project-monitors: My project is ready!'*

        Thank you!

        *After submission, we will assign a 'project monitor' to follow your submission. If at any time you need help or anything is unclear, please add a comment and ping your project monitor. Our team is here to help!*
        
  - type: input
    id: title
    attributes:
      label: Title
      description: Name of your awesome project. Please also update the title of the issue to be the title of your project
    validations:
      required: true
      
  - type: textarea
    id: project-leads
    attributes:
      label: Project lead
      description: Your name and GitHub login, possibly more than 1 lead
      placeholder: One per line
    validations:
      required: true
      
  - type: dropdown
    id: hub
    attributes:
      label: Hub
      description: The Hackathon Hub your availability fits better.
      options:
        - Glasgow
        - Asia / Pacific
        - Europe / Middle East / Africa
        - Americas
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to Project
    validations:
      required: false

  - type: input
    id: goals
    attributes:
      label: Goals for the OHBM BrainHack
    validations:
      required: true
      
  - type: textarea
    id: skills
    attributes:
      label: Skills
    validations:
      required: true
      
  - type: input
    id: website-image
    attributes:
      label: Image for the OHBM brainhack website
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ## Project submission

        ## Submission checklist
        *Once the issue is submitted, please check items in this list as you add under 'Additional project info'*

  - type: checkboxes
    id: checklist
    attributes:
      label:
      description: Please include the following above (all required)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
