name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

  issues:
    - edited
    - labeled

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - run: pip install -r requirements.txt

      - name: Fetching projects from GitHub
        run: python scripts/fetch_gh_issues.py

      - name: Creating Discord channels
        run: python scripts/ensure_discord_channels.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

      # TODO script to tweet about the project
      #   (make sure we tweet only once about the project)

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'